# Generated by Django 5.2.17 on 2026-09-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_venues", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hometown", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followed_artists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.artist"
            ),
        ),
        migrations.CreateModel(
            name="ArtistMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("editor", "Editor")],
                        default="editor",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="events.artist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_artists",
                through="events.ArtistMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Promoter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followed_promoters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.promoter",
            ),
        ),
        migrations.CreateModel(
            name="PromoterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("editor", "Editor")],
                        default="editor",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promoter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="events.promoter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="promoter",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_promoters",
                through="events.PromoterMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VenueMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("editor", "Editor")],
                        default="editor",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="events.venue",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="venue",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_venues",
                through="events.VenueMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="artistmember",
            constraint=models.UniqueConstraint(
                fields=("artist", "user"), name="unique_artist_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotermember",
            constraint=models.UniqueConstraint(
                fields=("promoter", "user"), name="unique_promoter_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="venuemember",
            constraint=models.UniqueConstraint(
                fields=("venue", "user"), name="unique_venue_member"
            ),
        ),
    ]
