# Generated by Django 5.2.17 on 2026-09-28 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def city_names_to_cities(apps, schema_editor):
    City = apps.get_model("events", "City")
    Venue = apps.get_model("events", "Venue")
    for venue in Venue.objects.all():
        name = venue.city_name.strip() or "Berlin"
        city, _ = City.objects.get_or_create(slug=slugify(name), defaults={"name": name})
        venue.city = city
        venue.save(update_fields=["city"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_pages_members_follows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["name"],
            },
        ),
        # Venue.city was a plain text field; turn each distinct name into a City row.
        migrations.RenameField(model_name="venue", old_name="city", new_name="city_name"),
        migrations.AddField(
            model_name="venue",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venues",
                to="events.city",
            ),
        ),
        migrations.RunPython(city_names_to_cities, migrations.RunPython.noop),
        migrations.RemoveField(model_name="venue", name="city_name"),
        migrations.AlterField(
            model_name="venue",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venues",
                to="events.city",
            ),
        ),
        migrations.CreateModel(
            name="EventSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_venue_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="new venue"
                    ),
                ),
                (
                    "new_venue_address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="address"
                    ),
                ),
                (
                    "new_venue_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="district"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("ticket_url", models.URLField(blank=True)),
                (
                    "relation",
                    models.CharField(
                        help_text="For example: booker at the venue.",
                        max_length=200,
                        verbose_name="your role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, help_text="Sent to the submitter when you reject."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission",
                        to="events.event",
                    ),
                ),
                (
                    "new_venue_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="events.city",
                        verbose_name="city",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pick the venue, or fill in the new venue fields below.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="events.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
