# Generated by Django 5.2.17 on 2026-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="log_is_public",
            field=models.BooleanField(
                default=False,
                help_text="Let anyone with the link see the shows you went to, with your name, ratings and notes.",
                verbose_name="public log",
            ),
        ),
    ]
